on:
  repository_dispatch:
    types: [repository_created]

jobs:
  configure_repository:
    runs-on: ubuntu-latest
    if: github.event.organization == github.repository_owner
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
          REPO: ${{ github.event.client_payload.repository }}
        run: 
          echo $MESSAGE
          echo $REPO
